import type { TeacherSearchResult } from "./types";

export const teacherSearchSeed: TeacherSearchResult[] = [
  {
    id: "00000000-0000-0000-0000-000000000601",
    slug: "ayse-demir-matematik-erzurum",
    fullName: "Ayşe Demir",
    headline: "Erzurum Matematik Özel Ders",
    shortBio: "Yakutiye ve online matematik desteği. LGS ve TYT/AYT hazırlıkta planlı ilerleme.",
    city: "Erzurum",
    district: "Yakutiye",
    latitude: 39.9086,
    longitude: 41.2769,
    lessons: ["Matematik", "TYT / AYT"],
    deliveryMode: "both",
    hourlyPrice: 650,
    ratingAverage: 4.9,
    reviewCount: 18,
    experienceYears: 6,
  },
  {
    id: "00000000-0000-0000-0000-000000000602",
    slug: "mehmet-yilmaz-fizik-online",
    fullName: "Mehmet Yılmaz",
    headline: "Online Fizik Özel Ders",
    shortBio: "TYT/AYT fizik hazırlığı ve lise destek dersleri için online çalışma programı.",
    city: "İstanbul",
    district: "Kadıköy",
    latitude: 40.9919,
    longitude: 29.0278,
    lessons: ["Fizik", "TYT / AYT"],
    deliveryMode: "online",
    hourlyPrice: 900,
    ratingAverage: 0,
    reviewCount: 0,
    experienceYears: 4,
  },
  {
    id: "00000000-0000-0000-0000-000000000603",
    slug: "zeynep-acar-ingilizce-erzurum",
    fullName: "Zeynep Acar",
    headline: "Erzurum İngilizce Özel Ders",
    shortBio: "Palandöken çevresinde yüz yüze konuşma pratiği ve okul destek dersleri.",
    city: "Erzurum",
    district: "Palandöken",
    latitude: 39.8875,
    longitude: 41.2444,
    lessons: ["İngilizce"],
    deliveryMode: "face_to_face",
    hourlyPrice: 450,
    ratingAverage: 4.6,
    reviewCount: 7,
    experienceYears: 2,
  },
  {
    id: "00000000-0000-0000-0000-000000000604",
    slug: "deniz-kara-yazilim-ankara",
    fullName: "Deniz Kara",
    headline: "Yazılım ve Programlama Özel Ders",
    shortBio: "JavaScript, React ve algoritma temelleri için proje odaklı özel ders.",
    city: "Ankara",
    district: "Çankaya",
    latitude: 39.9179,
    longitude: 32.8627,
    lessons: ["Yazılım", "Matematik"],
    deliveryMode: "both",
    hourlyPrice: 1200,
    ratingAverage: 5,
    reviewCount: 23,
    experienceYears: 8,
  },
  {
    id: "00000000-0000-0000-0000-000000000605",
    slug: "elif-sahin-turkce-izmir",
    fullName: "Elif Şahin",
    headline: "Türkçe ve LGS Hazırlık",
    shortBio: "Okuma anlama, paragraf ve LGS Türkçe netlerini artırmaya yönelik program.",
    city: "İzmir",
    district: "Konak",
    latitude: 38.4192,
    longitude: 27.1287,
    lessons: ["Türkçe", "LGS"],
    deliveryMode: "online",
    hourlyPrice: 550,
    ratingAverage: 4.8,
    reviewCount: 11,
    experienceYears: 5,
  },
  {
    id: "00000000-0000-0000-0000-000000000606",
    slug: "burak-celik-kimya-erzurum",
    fullName: "Burak Çelik",
    headline: "Erzurum Kimya Özel Ders",
    shortBio: "Organik kimya, temel kavramlar ve sınav hazırlığı için yüz yüze ders.",
    city: "Erzurum",
    district: "Yakutiye",
    latitude: 39.9105,
    longitude: 41.2681,
    lessons: ["Kimya", "TYT / AYT"],
    deliveryMode: "face_to_face",
    hourlyPrice: 700,
    ratingAverage: 4.3,
    reviewCount: 4,
    experienceYears: 3,
  },
];

export const lessonOptions = ["Matematik", "Fizik", "Kimya", "İngilizce", "Türkçe", "Yazılım", "LGS", "TYT / AYT"];
export const cityOptions = ["Erzurum", "İstanbul", "Ankara", "İzmir"];
export const districtOptions = ["Yakutiye", "Palandöken", "Kadıköy", "Çankaya", "Konak"];
