import type { TeacherProfile } from "@/features/teachers/types";

export const teacherProfileSeed: TeacherProfile[] = [
  {
    id: "00000000-0000-0000-0000-000000000601",
    slug: "ayse-demir-matematik-erzurum",
    fullName: "Ayşe Demir",
    title: "Matematik Öğretmeni",
    headline: "Erzurum Matematik Özel Ders",
    shortBio: "Yakutiye ve online matematik desteği. LGS ve TYT/AYT hazırlıkta planlı ilerleme.",
    longBio:
      "Öğrencinin mevcut seviyesini ölçerek konu eksiklerini netleştiren, düzenli ödev ve takip planı ile ilerleyen birebir matematik dersleri veriyorum. LGS, TYT ve AYT hazırlığında soru çözüm tekniği, zaman yönetimi ve temel kavramları birlikte güçlendiriyoruz.",
    city: "Erzurum",
    district: "Yakutiye",
    latitude: 39.9086,
    longitude: 41.2769,
    lessons: ["Matematik", "TYT / AYT"],
    deliveryMode: "both",
    hourlyPrice: 650,
    lessonDurationMinutes: 60,
    ratingAverage: 4.9,
    reviewCount: 18,
    experienceYears: 6,
    education: "Atatürk Üniversitesi Matematik Öğretmenliği",
    responseTime: "Ortalama 2 saat içinde dönüş",
    activeStudentCount: 14,
    completedLessonCount: 240,
    isVerified: true,
    gender: "female",
    fastResponse: true,
    reviews: [
      {
        id: "00000000-0000-0000-0000-000000000701",
        studentName: "Merve K.",
        rating: 5,
        comment: "Konu eksiklerimi çok net belirledi ve düzenli takip etti.",
        createdAt: "2026-05-02",
      },
      {
        id: "00000000-0000-0000-0000-000000000702",
        studentName: "Ali T.",
        rating: 5,
        comment: "TYT matematikte netlerim kısa sürede arttı.",
        createdAt: "2026-04-18",
      },
    ],
  },
  {
    id: "00000000-0000-0000-0000-000000000602",
    slug: "mehmet-yilmaz-fizik-online",
    fullName: "Mehmet Yılmaz",
    title: "Fizik Öğretmeni",
    headline: "Online Fizik Özel Ders",
    shortBio: "TYT/AYT fizik hazırlığı ve lise destek dersleri için online çalışma programı.",
    longBio:
      "Fizik konularını formül ezberi yerine kavram, grafik ve örnek soru üzerinden anlatıyorum. Online derslerde ekran paylaşımı ve düzenli soru listeleriyle öğrencinin haftalık ilerlemesini takip ediyorum.",
    city: "İstanbul",
    district: "Kadıköy",
    latitude: 40.9919,
    longitude: 29.0278,
    lessons: ["Fizik", "TYT / AYT"],
    deliveryMode: "online",
    hourlyPrice: 900,
    lessonDurationMinutes: 60,
    ratingAverage: 0,
    reviewCount: 0,
    experienceYears: 4,
    education: "İstanbul Teknik Üniversitesi Fizik",
    responseTime: "Aynı gün içinde dönüş",
    activeStudentCount: 8,
    completedLessonCount: 96,
    isVerified: true,
    gender: "male",
    fastResponse: true,
    reviews: [],
  },
  {
    id: "00000000-0000-0000-0000-000000000603",
    slug: "zeynep-acar-ingilizce-erzurum",
    fullName: "Zeynep Acar",
    title: "İngilizce Öğretmeni",
    headline: "Erzurum İngilizce Özel Ders",
    shortBio: "Palandöken çevresinde yüz yüze konuşma pratiği ve okul destek dersleri.",
    longBio:
      "Konuşma pratiği, okul derslerine destek ve sınav hazırlığı için öğrencinin seviyesine göre ders planı oluşturuyorum. Derslerde kelime, telaffuz ve günlük kullanım ağırlıklı ilerliyorum.",
    city: "Erzurum",
    district: "Palandöken",
    latitude: 39.8875,
    longitude: 41.2444,
    lessons: ["İngilizce"],
    deliveryMode: "face_to_face",
    hourlyPrice: 450,
    lessonDurationMinutes: 60,
    ratingAverage: 4.6,
    reviewCount: 7,
    experienceYears: 2,
    education: "Anadolu Üniversitesi İngilizce Öğretmenliği",
    responseTime: "Ortalama 4 saat içinde dönüş",
    activeStudentCount: 6,
    completedLessonCount: 72,
    isVerified: false,
    gender: "female",
    fastResponse: false,
    reviews: [
      {
        id: "00000000-0000-0000-0000-000000000703",
        studentName: "Ece A.",
        rating: 5,
        comment: "Konuşma pratiğinde çok destek oldu.",
        createdAt: "2026-03-29",
      },
    ],
  },
  {
    id: "00000000-0000-0000-0000-000000000604",
    slug: "deniz-kara-yazilim-ankara",
    fullName: "Deniz Kara",
    title: "Yazılım Eğitmeni",
    headline: "Yazılım ve Programlama Özel Ders",
    shortBio: "JavaScript, React ve algoritma temelleri için proje odaklı özel ders.",
    longBio:
      "Programlama derslerini gerçek proje parçaları üzerinden işliyorum. Öğrencinin seviyesine göre temel algoritma, JavaScript, React ve portfolyo hazırlığı konularında düzenli çalışma planı oluşturuyorum.",
    city: "Ankara",
    district: "Çankaya",
    latitude: 39.9179,
    longitude: 32.8627,
    lessons: ["Yazılım", "Matematik"],
    deliveryMode: "both",
    hourlyPrice: 1200,
    lessonDurationMinutes: 60,
    ratingAverage: 5,
    reviewCount: 23,
    experienceYears: 8,
    education: "Orta Doğu Teknik Üniversitesi Bilgisayar Mühendisliği",
    responseTime: "Ortalama 1 saat içinde dönüş",
    activeStudentCount: 18,
    completedLessonCount: 310,
    isVerified: true,
    gender: "male",
    fastResponse: true,
    reviews: [
      {
        id: "00000000-0000-0000-0000-000000000704",
        studentName: "Can B.",
        rating: 5,
        comment: "React konularını proje üzerinden çok anlaşılır anlattı.",
        createdAt: "2026-04-11",
      },
    ],
  },
  {
    id: "00000000-0000-0000-0000-000000000605",
    slug: "elif-sahin-turkce-izmir",
    fullName: "Elif Şahin",
    title: "Türkçe Öğretmeni",
    headline: "Türkçe ve LGS Hazırlık",
    shortBio: "Okuma anlama, paragraf ve LGS Türkçe netlerini artırmaya yönelik program.",
    longBio:
      "Türkçe derslerinde okuma-anlama, paragraf çözümü, dil bilgisi ve sınav stratejisini birlikte ele alıyorum. Öğrencinin hatalarını düzenli takip ederek tekrar planı hazırlıyorum.",
    city: "İzmir",
    district: "Konak",
    latitude: 38.4192,
    longitude: 27.1287,
    lessons: ["Türkçe", "LGS"],
    deliveryMode: "online",
    hourlyPrice: 550,
    lessonDurationMinutes: 60,
    ratingAverage: 4.8,
    reviewCount: 11,
    experienceYears: 5,
    education: "Ege Üniversitesi Türkçe Öğretmenliği",
    responseTime: "Aynı gün içinde dönüş",
    activeStudentCount: 10,
    completedLessonCount: 134,
    isVerified: true,
    gender: "female",
    fastResponse: true,
    reviews: [
      {
        id: "00000000-0000-0000-0000-000000000705",
        studentName: "Duru S.",
        rating: 5,
        comment: "Paragraf sorularında hız kazanmamı sağladı.",
        createdAt: "2026-05-07",
      },
    ],
  },
  {
    id: "00000000-0000-0000-0000-000000000606",
    slug: "burak-celik-kimya-erzurum",
    fullName: "Burak Çelik",
    title: "Kimya Öğretmeni",
    headline: "Erzurum Kimya Özel Ders",
    shortBio: "Organik kimya, temel kavramlar ve sınav hazırlığı için yüz yüze ders.",
    longBio:
      "Kimya derslerinde kavram temelli anlatım, örnek soru çözümü ve düzenli tekrar sistemiyle ilerliyorum. TYT/AYT hazırlık öğrencileri için haftalık hedef takibi yapıyorum.",
    city: "Erzurum",
    district: "Yakutiye",
    latitude: 39.9105,
    longitude: 41.2681,
    lessons: ["Kimya", "TYT / AYT"],
    deliveryMode: "face_to_face",
    hourlyPrice: 700,
    lessonDurationMinutes: 60,
    ratingAverage: 4.3,
    reviewCount: 4,
    experienceYears: 3,
    education: "Atatürk Üniversitesi Kimya",
    responseTime: "Ortalama 3 saat içinde dönüş",
    activeStudentCount: 5,
    completedLessonCount: 58,
    isVerified: false,
    gender: "male",
    fastResponse: false,
    reviews: [],
  },
];
